spring:
  application:
    name: portfolio-api

  datasource:
    url: jdbc:mysql://localhost:3306/rehan_portfolio
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

server:
  port: 8080